apiVersion: theodolite.rocks/v1beta1

kind: execution
metadata:
  name: teastorev26-example
spec:
  benchmark: teastorev26
  load:
    loadType: "NumUsers"
    loadValues: [1,2,3]
  resources:
    resourceType: "Instances"
    resourceValues: [1,3]
  slos:
    - name: "uiCPU"
    - name: "uiCPU"
  execution:
    strategy:
      name: "FullSearch"
    duration: 60  # in seconds
    loadGenerationDelay: 10  
    repetitions: 2
    stages: true
  configOverrides: []

