apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter
  annotations:
    openservicemesh.io/sidecar-injection: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore
      app2: jmeter
      app.kubernetes.io/name: jmeter
      app.kubernetes.io/component: load-gen
  template:
    metadata:
      labels:
        monitoring: enabled
        app: teastore
        app2: jmeter
        app.kubernetes.io/name: jmeter
        app.kubernetes.io/component: load-gen
    spec:
      containers:
        - name: jmeter
          image: justb4/jmeter
          command:
            - "/bin/bash"
            - "-c"
            - "-n"  
            - |
              java -jar bin/ApacheJMeter.jar \
              -t profile/teastore_browse_rps.jmx \
              -Jhostname teastore-webui \
              -Jport 8080;
              sleep 3600  
          volumeMounts:
            - name: jmeter-profile
              mountPath: /opt/apache-jmeter-5.5/profile
      volumes:
        - name: jmeter-profile
          configMap:
            name: teastore-jmeter-browse-rps

