server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: kubernetes-services
    kubernetes_sd_configs:
      - role: service

    relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_run]
      action: keep
      regex: 'teastore-kieker-rabbitmq'  # Replace with your pod label

    pipeline_stages:
    - docker: {}

    - regex:
        expression: '^\$(\d+);(\d+);(.*?);(.*?);(\d+);(\d+);(\d+);(.*?);(\d+);(\d+)'

    - labels:
        flag: "$1"
        timestamp: "$2"
        method: "$3"
        session_id: "$4"
        some_id: "$5"
        another_timestamp: "$6"
        yet_another_timestamp: "$7"
        pod_name: "$8"
        pod_id: "$9"
        some_field: "$10"

    - output:
        source: message


    - timestamp:
        source: timestamp
        format: UnixMs

