apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-kieker-rabbitmq
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-kieker-rabbitmq
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-kieker-rabbitmq
    spec:
      containers:
      - name: teastore-kieker-rabbitmq
        image: descartesresearch/teastore-kieker-rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 8080
        - containerPort: 15672
      - name: promtail
        image: grafana/promtail:latest
        args:
          - "-config.file=/etc/promtail/promtail.yaml"
        volumeMounts:
          - name: promtail-config
            mountPath: /etc/promtail
          - name: rabbitmq-logs
            mountPath: /apache-tomcat-8.5.24/webapps/logs
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: rabbitmq-logs
